# Generated by Django 3.0.8 on 2020-08-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='')),
                ('input_trimap', models.ImageField(upload_to='')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('output_trimap', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
