# Generated by Django 3.0.8 on 2020-10-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIM_API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InputImage',
        ),
    ]
